name: Publish Docs

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"
      working-directory:
        type: string
        default: "."

jobs:
  deploy:
    name: Publish Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Compute cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ${{ inputs.working-directory }}/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
